### ISSUE TITLE
PV Ampere result wrong by factor of 10

### ISSUE THREAD

**Issue by nick-prater** [creagraphy/sb_bt#3]
Thanks for the software.

I'm using with a SunnyBoy 3000TL.
Running on the command line, the PV Ampere value reported is a factor of 10 too high.

For example it reports 10.26, when the correct value is 1.026.

Fix to follow.

**Comment by creagraphy** [comment]
Hi Nick,

Thanks for using my software and sorry for the late response. Also thanks for your fix.

I suspect the factor is device dependent, because the values are correct for my SunnyBoy 2100TL. For example the current values all seem ok:
Current kW: 0.273
Current Net Volt: 238.40
Net Ampere: 1.148

Perhaps we should build a table of device types and factors, but that seems like a lot of work (especially to find all the device specifics)

For the moment I will not apply your update, as it might give problems for people with other devices than yours. I will make a note in the readme though.

Thanx again!

Ernst

**Comment by creagraphy** [comment]
Thanks for using my software and your update.

You are right, for some reason I missed this bug. Probably because the CSV output did have the correct values.

I will pull your change.

Thanks a lot!

Ernst.
